apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-volume-r2
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  autoPlace: "2"
  storagePool: lvm-thin
