apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linstor-volume-pvc
  namespace: default
spec:
  storageClassName: linstor-volume-r2
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
