apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-volume-r2
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  placementCount: "2"
  placementPolicy: AutoPlace
  allowRemoteVolumeAccess: "true"
  disklessOnRemaining: "false"
  storagePool: lvm-thin
